MYSQL_HOST: park-db
MYSQL_PORT: 3306
MYSQL_USERNAME: services
MYSQL_PASSWORD: services@2020
DB_AUTH: services
DB_USER: services
DB_EXAM: services
DB_GATEWAY: services
REDIS_HOST: park-03
REDIS_PORT: 28001
RABBIT_HOST: park-02


server:
  port: 9190
spring:
  application:
    name: webcast-service
  servlet:
    multipart:
      # 单个文件的大小
      max-file-size: 200MB
      # 单次请求的文件的总大小
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_USER:microservice-user}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: bdsjz@1234!
  boot:
    admin:
      client:
        url: http://${ADMIN_HOST:localhost}:${ADMIN_PORT:9186}/admin
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:11}
        instance:
          service-base-url: http://${AUTH_SERVICE_HOST:localhost}:${server.port}
          metadata:
            tags:
              environment: prd

security:
  oauth2:
    client:
      client-id: web_app
      client-secret: $2a$10$S84wOzmAw4wqYBzAqNtmPOx1ZRWdDl9omm/W8T1hhW8S9EK2u57xG
      access-token-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/authorize
      grant-type: password
      scope: read
    resource:
      user-info-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/user/v1/user/info
      prefer-token-info: false
      jwt:
        key-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjxSawA+NUNmhB2ctiVnt
          YH41WCNoD5STW2iPm5AIsKvm6X67lr6A88qOMRwx9oySdZnUnJ+8L3QJ51fkwuDe
          ix5w9yA3f/7LUPWZU8M/7Oi+2nda05JMgU999TUlhTGsp9SPiBqq/iwuqMxU8xKu
          F8bpTJTOpzrxH4e5BM6J/UJcOwDZLY6/3zP5w+tbhTvxjc995G4NtUyS4owE1MHe
          lj8IJepknjePrE6nXD6ecdL401hstMY838UOOFiCnM8NpiBuNI0nY0qCbb9mhQZ+
          7gP3jjM+Ft7R+MFTuEHWQ5UN8qHAPIT9UlLcu9IXdk6YwTsqNavwaTLUcP/ih9HB
          6wIDAQAB
          -----END PUBLIC KEY-----

# ===================================================================
# 七牛云存储配置
# ===================================================================
qiniu:
  access-key: ${QINIU_ACCEESS_KEY:test}
  secret-key: ${QINIU_SECRET_KEY:test}
  bucket: microservice-exam
  domain-of-bucket: ${QINIU_DOMAIN:test}
  expire: 3600  # 链接超时时间，单位秒，默认一小时

# 华为obs云存储配置
hwobs:
  end-point: obs.cn-south-1.myhuaweicloud.com
  access-key: WKAVDXACIKZ7ZPJATE1H
  secret-key: 7Oqjtry2uBe8eJv4ncCTSNWNl6fBgXERWQGJFHPQ

# feign相关配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled:  true

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# 直播配置 测试环境
webcast:
  userId: ${WEBCAST_USER_ID:e533868428}
  appId: ${WEBCAST_APP_ID:fu8nu88dq4}
  appSecret: ${SMS_APP_SECRET:df72b6e943d240a0a3ebc0929d485076}
# 直播配置 正式环境
#webcast:
#  userId: ${WEBCAST_USER_ID:5c925622ab}
#  appId: ${WEBCAST_APP_ID:fxmy56nsfe}
#  appSecret: ${SMS_APP_SECRET:613c1c2360f34489bdf1e6410305de70}

# mybatis配置
mybatis:
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 延迟加载
    lazy-loading-enabled: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /hystrix.sender
    - /v1/webcast/**
    - /**/*.css
    - /**/*.js
    - /info
    - /health
    - /metrics/**
    - /loggers/**

# 集群ID生成配置
cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}

eureka:
  client:
    service-url:
      defaultZone: http://park:654321@localhost:7641/eureka
poy:
  callBackUrl: http://39.100.11.213:9180/api/webcast/v1/AsyncCallBack/callBack
  #正式环境 callBackUrl: http://39.100.11.213:9180/api/webcast/v1/AsyncCallBack/callBack