server:
  port: 9993

spring:
  datasource:
    url: jdbc:mysql://39.100.11.213:3306/work_order?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: BDhY4VUITOtp4iuD0GGq

  jpa:
    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true

  redis:
    host: 101.32.184.222
    port: 6379

icepoint:
  web:
    security:
      ignore-paths:
        - /**

logging:
  level:
    org.hibernate.type: trace

agile-bpm:
  context-path: /bpm
  port: 8080
  host: 127.0.0.1
  protocol: http
  database: agilebpm_test