MYSQL_HOST: 192.168.0.98
MYSQL_PORT: 3306
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
DB_AUTH: exam
DB_USER: exam
DB_EXAM: exam
DB_GATEWAY: exam
DB_BASE: exam
REDIS_HOST: 192.168.0.98
REDIS_PORT: 28001

server:
  port: 9185
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_BASE:microservice-exam}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: bdsjz@1234!
  data:
    redis:
      repositories:
        enabled: false
    jdbc:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: false
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:bdsjz@1234!}
  boot:
    admin:
      client:
        url: http://${ADMIN_HOST:localhost}:${ADMIN_PORT:9186}/admin
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:11}
        instance:
          service-base-url: http://${EXAM_SERVICE_HOST:localhost}:${server.port}
          metadata:
            tags:
              environment: prd
  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
    # zipkin 配置
    #zipkin:
    # base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}  # 指定了Zipkin服务器的地址
  servlet:
    multipart:
      # 单个文件的大小
      max-file-size: 10MB
      # 单次请求的文件的总大小
      max-request-size: 100MB

security:
  oauth2:
    client:
      client-id: web_app
      client-secret: $2a$10$S84wOzmAw4wqYBzAqNtmPOx1ZRWdDl9omm/W8T1hhW8S9EK2u57xG
      access-token-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/authorize
      grant-type: password
      scope: read
    resource:
      user-info-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/user/v1/user/info
      prefer-token-info: false
      jwt:
        key-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjxSawA+NUNmhB2ctiVnt
          YH41WCNoD5STW2iPm5AIsKvm6X67lr6A88qOMRwx9oySdZnUnJ+8L3QJ51fkwuDe
          ix5w9yA3f/7LUPWZU8M/7Oi+2nda05JMgU999TUlhTGsp9SPiBqq/iwuqMxU8xKu
          F8bpTJTOpzrxH4e5BM6J/UJcOwDZLY6/3zP5w+tbhTvxjc995G4NtUyS4owE1MHe
          lj8IJepknjePrE6nXD6ecdL401hstMY838UOOFiCnM8NpiBuNI0nY0qCbb9mhQZ+
          7gP3jjM+Ft7R+MFTuEHWQ5UN8qHAPIT9UlLcu9IXdk6YwTsqNavwaTLUcP/ih9HB
          6wIDAQAB
          -----END PUBLIC KEY-----

# mybatis配置
mybatis:
  type-aliases-package: com.github.tangyi.exam.api.module
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 延迟加载
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 系统配置
sys:
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天
  logoUrl: /static/img/exam
  logoCount: 22
  logoSuffix: .jpeg
  qrCodeUrl: http://${QR_CODE_URL:localhost}:${QR_CODE_PORT:8080}/#/mobile
  adminUser: ${ADMIN_USER:admin}  # 管理员账号，默认是admin
  uploadUrl: api/file/v1/attachment/upload
  defaultAvatar: /static/img/avatar/
  key: '1234567887654321'
  attachUploadType: 4  # 上传类型，1：本地目录，2：fastDfs，3：七牛云  4 华为obs
  attachPath: ${ATTACH_PATH:/home/park/attach} # 附件上传目录
  canPreview: jpg,png,jpeg,gif # 支持预览的格式

# feign相关配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled:  true

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

ignore:
  urls:
    - /actuator/health
    #    - /generic/**
    #    - /resource/**
    #    - /sys/**
    #    - /test/**

    - /sys/file/**
    - /generic/entity/affairOpen/get
    - /generic/entity/recordEvents/get
    - /generic/entity/basicInfo/get
    - /generic/entity/webPhoto/get
    - /generic/entity/cboPolicy/get
    - /generic/entity/cboItem/get
    - /generic/entity/cboDynamic/get
    - /generic/entity/landPublicity/get
    - /generic/entity/discountEnt/get
    - /generic/entity/profileManage/get
    - /generic/entity/myInvest/get
    - /generic/entity/supplyDemand/get
    - /generic/entity/certificateStaff/get
    - /generic/entity/keyEnt/get
    - /generic/entity/affairOpen/page
    - /generic/entity/recordEvents/page
    - /generic/entity/basicInfo/page
    - /generic/entity/webPhoto/page
    - /generic/entity/cboPolicy/page
    - /generic/entity/cboItem/page
    - /generic/entity/cboDynamic/page
    - /generic/entity/landPublicity/page
    - /generic/entity/discountEnt/page
    - /generic/entity/profileManage/page
    - /generic/entity/myInvest/page
    - /generic/entity/supplyDemand/page
    - /generic/entity/certificateStaff/page
    - /generic/entity/keyEnt/page
    - /generic/entity/organization/get
    - /generic/entity/organization/page
    - /generic/entity/entInformation/list
    - /generic/entity/exhaustEmission/list
    - /generic/entity/sewageDischarge/list
    - /generic/entity/energyConsumption/list
    - /generic/entity/dataQuarter/page
    - /generic/entity/gasSupply/page
    - /generic/entity/accidentCases/get
    - /generic/entity/accidentCases/list
    - /generic/entity/accidentCases/page
    - /generic/entity/dangChemicals/get
    - /generic/entity/dangChemicals/list
    - /generic/entity/dangChemicals/page
    - /generic/entity/disposalMethod/get
    - /generic/entity/disposalMethod/list
    - /generic/entity/disposalMethod/page
    - /generic/entity/unitFunction/get
    - /generic/entity/unitFunction/list
    - /generic/entity/unitFunction/page
    - /generic/entity/laborNeed/get
    - /generic/entity/laborNeed/list
    - /generic/entity/laborNeed/page
    - /generic/entity/aqhbyj/get
    - /generic/entity/aqhbyj/page
    - /generic/entity/aqhbyj/list
    - /generic/entity/partyNews/get
    - /generic/entity/partyNews/page
    - /generic/entity/partyNews/list
    - /generic/entity/onlineShowroom/get
    - /generic/entity/onlineShowroom/page
    - /generic/entity/onlineShowroom/list
    - /generic/entity/partyGateway/get
    - /generic/entity/partyGateway/page
    - /generic/entity/partyGateway/list
    - /generic/entity/partyLook/get
    - /generic/entity/partyLook/page
    - /generic/entity/partyLook/list
    - /generic/entity/partyGuide/get
    - /generic/entity/partyGuide/page
    - /generic/entity/partyGuide/list
    - /generic/entity/partyFeature/get
    - /generic/entity/partyFeature/page
    - /generic/entity/partyFeature/list
    - /generic/entity/dataBase/get
    - /generic/entity/dataBase/page
    - /generic/entity/dataBase/list
    - /generic/entity/literarySelections/get
    - /generic/entity/literarySelections/page
    - /generic/entity/literarySelections/list
    - /generic/entity/lndustryInformation/get
    - /generic/entity/lndustryInformation/page
    - /generic/entity/lndustryInformation/list
    - /generic/entity/resultsReport/get
    - /generic/entity/resultsReport/page
    - /generic/entity/resultsReport/list
    - /generic/entity/safetyLicense/get
    - /generic/entity/safetyLicense/page
    - /generic/entity/safetyLicense/list
    - /generic/entity/safeQualification/get
    - /generic/entity/safeQualification/page
    - /generic/entity/safeQualification/list
    - /generic/entity/safeProduction/get
    - /generic/entity/safeProduction/page
    - /generic/entity/safeProduction/list
    - /generic/entity/dischargePermit/get
    - /generic/entity/dischargePermit/page
    - /generic/entity/dischargePermit/list
    - /generic/entity/annualTax/get
    - /generic/entity/annualTax/page
    - /generic/entity/annualTax/list
    - /sys/dict/list
    - /entp/info
    - /generic/entity/**/lastAndNest

# 集群ID生成配置
cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}

logging:
  level:
    com.github.tangyi: debug
    com.icepoint.base: debug

## 文件存储所需参数
# 所有通过 REST APIs 上传的文件都将存储在此目录下
file:
  upload-dir: ./uploads


# 统一认证的配置
ty:
  auth:
    # 授权url
    authorizeUrl: http://121.36.89.139/idaas/auth/oauth2/authorize
    # 用授权码换token 的Url
    tokenUrl: http://121.36.89.139/idaas/auth/oauth2/token
    # 登出url
    logoutUrl: http://121.36.89.139/idaas/auth/oauth2/logout
    # 客户端id
    clientId: 083OAJNKKLS45F7439F8FFABDF09AF98
    # 客户端密钥
    clientSecret: I909NUIHUIKDUABB92EF957D78686EC2
    # 回调uri 主系统配置的，若要修改，需要联系主系统的工程师（金证公司 的 杨辉）
    redirectUri: http://121.36.95.16/api/auth/v1/authentication/ty/callback
    # 获取用户信息
    getUserInfoUrl: http://121.36.89.139/idaas/manage/open-api/auth/user-info
    # 默认重定向到子系统的管理后台
    defaultRedirect: http://121.36.95.16/park/#/gateway

eureka:
  client:
    service-url:
      defaultZone: http://park:654321@park-01:7641/eureka,http://park:654321@park-02:7641/eureka