server:
  port: 9898
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://39.100.11.213:3306/icepoint_framework
    username: root
    password: BDhY4VUITOtp4iuD0GGq

icepoint:
  web:
    security:
      ignore-paths:
        - /test
