= 框架核心文档
:toc:

== 0. 概述
框架核心功能模块

== 1. 依赖
.Maven依赖
====
[source,xml]
----
<dependency>
    <groupId>com.icepoint.framework</groupId>
    <artifactId>icepoint-core</artifactId>
    <version>0.1-SNAPSHOT</version>
</dependency>
----
====

== 2. IO

=== 2.1 序列化相关

==== 2.1.1 序列化器基础接口：Serializer / Deserializer / StandardSerializer

- `Serializer` 只有一个序列化方法 `serialize()`，是序列化器的顶层接口。
- `Deserializer` 只有一个反序列化方法 `deserialize()`，是反序列化器的顶层接口。
- `Serializer` 和 `Deserializer` 都继承了接口 `SerializationExceptionHandlerProvider`，这个接口只有一个方法 `getExceptionHandler()`，用于处理序列化和反序列化中出现的异常。
- `StandardSerializer<S>` 包含序列化方法和反序列化方法，继承自 `Serializer` 和 `Deserializer`，`S` 是真正实现功能对象的类型。新增加了获取真正实现序列化和反序列化功能的对象的方法 `getSource()`；新增了支持泛型反序列的方法；新增了直接反序列化成字符串或者直接将字符串反序列的方法。

****
开发新的序列化器时，建议实现StandardSerializer，因为它的功能是基本齐全的，使用的时候会比较方便。
****

==== 2.1.2 基于Jackson的实现： ObjectMapperSerializer

针对jackson的 `ObjectMapper`，做了基础的实现，根据构建时传入的 `ObjectMapper` 的具体实现，即可实现不同序列化功能。

==== 2.1.3 静态工具类：Serializers

用于获取不同类型序列化器的工具类，目前以配置的有针对XML的和JSON的序列化器。

.Serializers
====
[source]
----
Serializers.json().serialize(outputStream, object); <1>

Serializers.xml().deserialize(inputStream, ValueType.class); <2>
----
<1> 使用JSON序列化器序列化对象
<2> 使用XML序列化器反序列化对象
====

== 3. 辅助功能类

=== 3.1 TimeRange

这是一个包含开始时间和结束时间的对象，用于表示一个准确的时间范围，内含时间格式化器，可以直接获取格式化后的时间字符串，也可以获取开时间和结束时间之间的时间长度对象 `Duration`。

.TimeRange
====
[source]
----
TimeRange timeRange = TimeRange.of(start, end); <1>

LocalDateTime start = timeRange.getStart(); <2>

long endMills = timeRange.getEndMills(); <3>

timeRange.setDefaultFormatter(DateTimeFormatter.ISO_DATE_TIME); <4>

String startStr = timeRange.getStartStr(); <5>

String startStr = timeRange.getEndStr(DateTimeFormatter.ISO_DATE); <6>

Duration duration = timeRange.getDuration(); <7>
----
<1> 用开始时间 `start` 和结束时间 `end` 构建一个 `TimeRange` 对象。
<2> 获取开始时间。
<3> 获取结束时间戳。
<4> 设置默认的时间格式化器为 `DateTimeFormatter.ISO_DATE_TIME`，即便不设置自身也会自带一个时间格式化器，格式是： `yyyy-MM-dd HH:mm:ss`。
<5> 使用默认的时间格式化器，获取开始时间字符串。
<6> 使用也定的时间格式化器 `DateTimeFormatter.ISO_DATE`，获取结束时间字符串。
<7> 获取开始时间和结束时间之间的时长对象 `Duration`。
====

=== 3.2 TimeRanges

方便构造 `TimeRange` 对象的工具类。

.TimeRanges
====
[source]
----
LocalDateTime dateTime = LocalDateTime.now();

TimeRange year = TimeRanges.year(dateTime); <1>

TimeRange month = TimeRanges.month(dateTime); <2>

TimeRange week = TimeRanges.week(dateTime); <3>

TimeRange workday = TimeRanges.workday(dateTime); <4>

TimeRange day = TimeRanges.day(dateTime); <5>

TimeRange hour = TimeRanges.hour(dateTime); <6>
----
<1> 构建包含 `dateTime` 对应的年份的 `TimeRange` 对象
<2> 构建包含 `dateTime` 对应的月份的 `TimeRange` 对象
<3> 构建包含 `dateTime` 对应的周的 `TimeRange` 对象
<4> 构建包含 `dateTime` 对应的工作日的 `TimeRange` 对象
<5> 构建包含 `dateTime` 对应的日期的 `TimeRange` 对象
<6> 构建包含 `dateTime` 对应的小时的 `TimeRange` 对象
====