= Web系统模块
:toc:

== 0. 概述

以项目的维度构建的web模块，包括项目、模块、函数、数据实体等的元数据定义，以及通用接口等。

== 1. 依赖

.Maven依赖
====
[source,xml]
----
<dependency>
    <groupId>com.icepoint.framework</groupId>
    <artifactId>icepoint-web-system</artifactId>
    <version>0.1-SNAPSHOT</version>
</dependency>
----
====

== 2. 通用接口

通用接口需要配置一个请求路径，增删改查都是根据请求路径+RESTFUL标准来进行设计的。

例如现在有一个通用接口为：/sample，那么该接口增删改查的请求方式如下

|===
|请求方法 |请求路径 |说明

|GET
|/sample
|查询列表，如果带分页参数，则是查询分页，分页参数分别是页码 `page` 和条数 `size`，`page` 从0开始，注意分页参数必须放在url参数上

|GET
|/sample/\{id}
|根据id查询

|POST
|/sample
|新增数据，参数放到请求体中

|PATCH
|/sample
|根据id进行局部更新，也是没有传的字段不会被更新，传的字段即便为 `null` ，也会进行更新

|PUT
|/sample
|根据id进行全量更新，没有传的字段会被设置为 `null`

|DELETE
|/sample/\{id}
|根据id删除数据，会根据配置自动进行物理删除或者逻辑删除
|===

所有GET请求均可添加查询参数，参数全部放在url参数上，简单的参数可以直接字段=值的方式进行查询。

复杂的条件查询的参数名是 `_query`，里面需要传递一个表达式。其中有可能会有部分字符需要用URI编码进行编码。

通用查询有一个概念叫 `path`，简单来说就是要查询的字段名，但也不完全相同，可以暂且当作是查询的字段名来看，后面会做详细解释。

=== 2.1 单条件查询

最基础的表达式格式是: `{path} {operator} {value}`。

* `{path}`: 查询的字段名
* `{operator}`: 查询的条件
* `{value}`: 查询的值

.支持的operator
|===
| Operator(不区分大小写) | 作用 | 说明

|eq
|等于
|支持所有数据类型

|ne
|不等于
|支持所有数据类型

|gt
|大于
|支持时间或者数字类型

|ge
|大于等于
|同上

|lt
|小于
|同上

|le
|小于等于
|同上

|like
|模糊查询
|需要添加匹配符"%"，例如完全模糊查询是"%lookup%"

|between
|区间查询
|逗号分隔，如"5, 10"

|in
|多值查询等于
|逗号分隔，如"1, 3, 5, 7"

|notin
|多值查询不等于
|逗号分隔，如"1, 3, 5, 7"
|===

.单条件查询表达式
====
[source]
----
text eq hello <1>
number gt 5 <2>
number between 5, 10 <3>
text in hello, world, icepoint <4>
text like %hello% <5>
----
<1> 查询字段 `text` 字段等于 `hello` 的数据，类似: `text == "hello"`
<2> 查询字段 `number` 等于 `5` 的数据，类似 : `number > 5`
<3> 查询字段 `number` 大于等于 `5` 小于等于 `10` 的数据，类似: `number >= 5 && number \<= 10`
<4> 查询字段 `text` 等于 `"hello"` 或 `"world"` 或 `"icepoint"` 的数据，类似: `text == "hello" || text == "world" || text == "icepoint"`
<5> 查询字段 `text` 含有 `"hello"` 的数据
====

=== 2.2 多条件查询

在单条件的基础上，增加 `{connector}`，如：

`{path} {operator} {value} {connector} {path} {operator} {value}`

支持的 `{connector}` :

* `&&`: 与
* `||`: 或

.多条件查询表达式
====
[source]
----
text eq hello && number gt 5 <1>
number between 5, 10 && number ne 8 <2>
----
<1> 查询字段 `text` 字段等于 `hello` 的数据，类似: `text == "hello && number > 5"`
<2> 查询字段 `number` 大于等于5，小于等于10，并且不等于8的数据，类似: `number >= 5 && number \<= 5 && number != 8`
====

=== 2.3 查询路径path

`path` 跟简单的字段名不同的地方在于，`path` 是基于表关联的基础上，对字段的查询增加有深度的关联查询的功能。

.关联查询
====
例如现在有老师 (Teacher) 和学生 (Student) 两个表，它们都有一个字段 `name`，它们是多对多的关联关系。

通用查询接口是直接对应表的，而如果现在要查询所有老师中，有学生的 `name` 是 `Mark` 的，那么此时调用老师表的通用接口，要查询的path就可以是:

[source]
----
students.name eq Mark <1>
----
<1> 这里也会涉及到"根节点"的概念，例如这里的 `students`，是基于根节点 `Teacher` 的，是 `Teacher` 关联的 `Student`，类似于: `teacher.students`
====