MYSQL_HOST: park-db
MYSQL_PORT: 3306
MYSQL_USERNAME: services
MYSQL_PASSWORD: Abc@12345
DB_AUTH: services
DB_USER: services
DB_EXAM: services
DB_GATEWAY: services
REDIS_HOST: park-03
REDIS_PORT: 28001
REDIS_PASSWORD: bdsjz@1234!
RABBIT_HOST: park-02

server:
  port: 9191
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
      host: ${RABBIT_HOST:localhost}
      port: ${RABBIT_PORT:5672}
      virtual-host: my_vhost
      username: admin
      password: bdsjz@1234!
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_USER:microservice-user}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

  # feign相关配置
  feign:
    httpclient:
      enabled: false
    okhttp:
      enabled: true
    hystrix:
      enabled:  true

  # hystrix配置
  hystrix:
    shareSecurityContext: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS
  # mybatis配置
  mybatis:
    configuration:
      # 驼峰转换
      map-underscore-to-camel-case: true
      # 延迟加载
      lazy-loading-enabled: true
    mapper-locations: classpath:mapper/*.xml
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

  ignore:
    urls:
      - /
      - /error
      - /favicon.ico
      - /**/*swagger*/**
      - /v2/api-docs
      - /csrf
      - /actuator/**
      - /hystrix.sender
      - /v1/sms/**
      - /**/*.css
      - /**/*.js
      - /info
      - /health
      - /metrics/**
      - /loggers/**
      - /v1/sms/**

  # 集群ID生成配置
cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}

# wx开发者账号配置
wx_appid: wx6657b10e4ca6b0c9
wx_appsecret: a5a6695dcffd2df0a5dba0d26373d73d
eureka:
  client:
    service-url:
      defaultZone: http://park:654321@park-02:7641/eureka
